help:       ## Show this help.
	@fgrep -h "##" $(MAKEFILE_LIST) | fgrep -v fgrep |

catalouge:	##Install Catalouge
	@bash components/catalouge.sh

mongodb:	##Install Mongodb
	@bash components/mongodb.sh

redis:		##Install Redis
	@bash components/redis.sh

user:		##Install User
	@bash components/user.sh

cart:		##Install Cart
	@bash components/cart.sh

mysql:		##Install Mysql
	@bash components/mysql.sh

shipping:	##Install Shipping
	@bash components/shipping.sh

rabbitmq:	##Install Rabbitmq
	@bash components/rabbitmq.sh

payment:	##Install Payment
	@bash components/payment.sh

frontend:	##Install Forntend
	@bash components/frontend.sh

####
testing